// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACUp2e0eMW5lbJIGx3CxmncPEv7ub99EM',
    appId: '1:392443274937:web:8c4b30d70f8173ec511d68',
    messagingSenderId: '392443274937',
    projectId: 'fog-o-war',
    authDomain: 'fog-o-war.firebaseapp.com',
    storageBucket: 'fog-o-war.appspot.com',
    measurementId: 'G-FZKLMGTF1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7F0mAmkp8W8WngeWjAsV5wKRHYRQ0Fes',
    appId: '1:392443274937:android:41fa735ea4c16743511d68',
    messagingSenderId: '392443274937',
    projectId: 'fog-o-war',
    storageBucket: 'fog-o-war.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAngcNQwFW7Ys2wGq5QKLsV4PNBAWOFLQ4',
    appId: '1:392443274937:ios:8c626357fa4ca8ae511d68',
    messagingSenderId: '392443274937',
    projectId: 'fog-o-war',
    storageBucket: 'fog-o-war.appspot.com',
    iosBundleId: 'com.example.goSocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAngcNQwFW7Ys2wGq5QKLsV4PNBAWOFLQ4',
    appId: '1:392443274937:ios:8c626357fa4ca8ae511d68',
    messagingSenderId: '392443274937',
    projectId: 'fog-o-war',
    storageBucket: 'fog-o-war.appspot.com',
    iosBundleId: 'com.example.goSocial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACUp2e0eMW5lbJIGx3CxmncPEv7ub99EM',
    appId: '1:392443274937:web:a2babb692e961fc2511d68',
    messagingSenderId: '392443274937',
    projectId: 'fog-o-war',
    authDomain: 'fog-o-war.firebaseapp.com',
    storageBucket: 'fog-o-war.appspot.com',
    measurementId: 'G-LMYVLWPY3N',
  );
}
